# sets the settings for correct pld generation


repository:
  owner: 'Chroma-Case'
  repo: 'Chromacase'
  milestoneNum: 6
  ignoredLabels:
    - 'ignored'
    - 'Draft'

members:
  - name: 'Louis Auzuret'
    ghUsername: 'GitBluub'
  - name: 'Zoe Roux'
    ghUsername: 'zoriya'
  - name: 'Arthur Jamet'
    ghUsername: 'Arthi-chaud'
  - name: 'Clément Le Bihan'
    ghUsername: 'Octopus773'
  - name: 'Amaury Danis Cousandier'
    ghUsername: 'AmauryDanisCousandier'
  - name: 'Chloé Chauvin'
    ghUsername: 'Nekory23'
  - name: 'Quentin Treheux'
    ghUsername: 'LuciferBahamut'
sprint:
    name: "Sprint Fast Forward"
    # dateFormat: 'DD-MM-YYYY'
    start: '02-01-2023'
    end: '25-05-2023'
doc:
  title: "PLD - Sprint Beta & Growth Hacking"
  object: "PLD du sprint Beta & Growth Hacking"
  author: "Clément LE BIHAN"
  manager: "Zoe Roux"
  email: "zoe1.roux@epitech.eu"
  keywords: 'User stories, fonctionnalités, tâches, sprint, DoD'
  promo: '2024'
  versions: 
    - date: '13-02-2023'
      num: '2.0'
      author: 'Clément Le Bihan'
      section: 'Toutes'
      comment: 'Nettoyage des détails de version'
    

lastSprintSummary: "Le séminaire de Forward nous a permis d’assurer, de
consolider nos idées, et d’ajuster notre valeur proposée sur
une technologie et une expérience innovante sur le marché.
Nous avons pu augmenter nos compétences en UI/UX en
présentant nos maquettes et nos échanges nous ont aidé à
comprendre les enjeux du design et de la production de
POC. Il nous a également permis de réaliser lorsque nous
faisions fausse route et donnions trop d’importance à des
concepts ou des idées peu pertinentes. Les
encouragements et ses remarques positives ont servi à
valider et invalider nos décisions."
progressReport:
  summary: ''
  blockingPoints: ''
  conclusion: ''
