# sets the settings for correct pld generation


repository:
  owner: 'Chroma-Case'
  repo: 'Chromacase'
  milestoneNum: 1
members:
  - name: 'Louis Auzuret'
    ghUsername: 'GitBluub'
  - name: 'Zoe Roux'
    ghUsername: 'AnonymusRaccoon'
  - name: 'Arthur Jamet'
    ghUsername: 'Arthi-chaud'
  - name: 'Clément Le Bihan'
    ghUsername: 'Octopus773'
  - name: 'Amaury Danis Cousandier'
    ghUsername: 'AmauryDanisCousandier'
doc:
  title: "PLD - Sprint Test & Learn"
  object: "PLD du sprint Test & Learn"
  author: "Clément LE BIHAN"
  manager: "Zoe Roux"
  email: "zoe1.roux@epitech.eu"
  keywords: 'User stories, fonctionnalités, tâches, sprint, DoD'
  promo: '2024'
  versions: 
    - date: '12-04-2022'
      num: '0.6.4'
      author: 'Arthur JAMET'
      section: 'Toutes'
      comment: 'Création du modèle'
    
    - date: '15-04-2022'
      num: '0.7.2'
      author: 'Clément LE BIHAN'
      section: 'Toutes'
      comment: 'Première version'
    
    - date: '20-04-2022'
      num: '0.8.1'
      author: 'Zoe Roux'
      section: 'Sommmaire'
      comment: 'Ajout du sommmaire'

    - date: '21-04-2022'
      num: '1.0.0'
      author: 'Clément Le Bihan'
      section: 'Stories'
      comment: 'Réparation de la partie description et Definition of Done'

    - date: '30-04-2022'
      num: '1.2.8'
      author: 'Clément Le Bihan'
      section: 'Stories'
      comment: "Ajout d'une couleur verte pour indiquer le fait que la storie soit terminée"
      
    - date: '25-05-2022'
      num: '1.2.9'
      author: 'Clément Le Bihan'
      section: 'Membres & Stories'
      comment: "Ajout d'Amaury dans le PLD et réassignation des personnes en conséquence"

lastSprintSummary: "Le séminaire de Forward nous a permis d’assurer, de
consolider nos idées, et d’ajuster notre valeur proposée sur
une technologie et une expérience innovante sur le marché.
Nous avons pu augmenter nos compétences en UI/UX en
présentant nos maquettes et nos échanges nous ont aidé à
comprendre les enjeux du design et de la production de
POC. Il nous a également permis de réaliser lorsque nous
faisions fausse route et donnions trop d’importance à des
concepts ou des idées peu pertinentes. Les
encouragements et ses remarques positives ont servi à
valider et invalider nos décisions."
progressReport:
  summary: ''
  blockingPoints: ''
  conclusion: ''
